#!/bin/bash
filename=$1

grep '8' $filename | tail -1
grep '7' $filename | tail -1
grep '6' $filename | tail -1
grep '5' $filename | tail -1
grep '4' $filename | tail -1
grep '3' $filename | tail -1
grep '2' $filename | tail -1
grep '1' $filename | tail -1
